language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: U4a4QzW3BjHI97guCC0/YXWIZBaKIz8Shzk1qwFLk0qXSI1tE/kXF/dJq52w5WAlq17Rnp6N3b2eeR5YpoRE9YIvPsjuEHfi6RttYA5SgTTRnbFrkc/EV0Y8ivpUdg+6gDVplFATTjAoeiyCdk00gX4RVpkPdMRnCOleWw1r+0E=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: AP5X5jFnZ4Gia5QBzCf8xRgMrMMxlVf+ru/RZJDP3Tt+K4a93/qN6eu2/+wThytEeIvuq6FnF6eyJeUtYxPwYoN8W5VUjtraIbWOJPz0IfMll9tsuvqv5Bn51FFcDoggw+iQJqTVlZvFoshC/AN0cL40/LMPR/xVKwhaVzPcLSI=
sudo: false
